# - * - codierung: utf-8 - * -
ITEM = [
'ein Bett, das',
'eine Yoga-Matte, die',
'einen Kalender, den',
'einen Lippenstift, den',
'eine Parkbank, die',
'ein Brettspiel, das',
'einen Schuh, den',
'ein Boot, das',
'ein Musik-Video, das',
'ein Radio, das',
'eine Möglichkeit, um Erinnerungen zu bewahren, die',
'ein Whiteboard, das',
'eine Halskette, die',
'eine Decke, die',
'einen Möglichkeit, um hohe Dinge zu erreichen, die',
'ein Musikinstrument, das',
'ein Vogelhaus, das',
'eine Geldbörse, die',
'eine Kamera, die',
'ein Spielzeug, das',
'ein Walkie-Talkie, das',
'eine Möglichkeit, Geld zu überweisen, die',
'eine Möglichkeit, um Nachrichten zu lesen, die',
'eine Gabel, die',
'ein Fahrzeug, das',
'einen Flaschenöffner, den',
'ein Buch, das',
'ein Kochbuch, das',
'eine Möglichkeit zur Abstimmung, die',
'eine Möglichkeit, um Pizza zu bestellen, die',
'eine Möglichkeit, um Ausgaben zu überwachen, die',
'eine Möglichkeit zum Protest, die',
'einen Trainingspartner, den',
'eine Kettensäge, die',
'eine Klobürste, die',
'eine Möglichkeit zum Einkaufen für Lebensmittel, die',
'eine Möglichkeit, um Zeit zu erzählen, die',
'einen Taschenrechner, den',
'eine Karte, die',
'eine Angelrute, die',
'eine Wettervorhersage, die'
'einen Gemüsegarten, den',
'eine Kaffeemaschine, die',
'eine Lampe, die',
'einen Papierkorb, den',
'ein Schloss, das',
'eine Möglichkeit, um Aktienkurse zu überprüfen, die',
'eine Mülltonne, die',
'einen Staubsauger, der',
'ein Zeichen der Liebe, das',
'eine Möglichkeit, um Fotos zu teilen, die',
'eine Möglichkeit, um Sport zu treiben, die',
'eine Waschmaschine, die',
'einen Rasierer, den',
'einen Geburtstagskuchen, den',
'einen Koffer, den',
'ein Fitnessgerät, das',
'einen Rasenmäher, den',
'einen Traktor, den',
'eine Zahnbürste, die',
'eine Toilettenpapierrolle, die',
'eine Zeitschrift, die',
'einen Badeanzug, den',
'eine Brille, die',
'einen Wasserkühler, den',
'eine Möglichkeit, um ein neues Auto zu kaufen, die',
'eine Grußkarte, die',
'ein Hochzeitskleid, das',
'einen Kiosk (Späti), den',
'ein Zelt, das',
'ein Skateboard, das',
'eine Schaufel, die',
'eine Teekanne, die',
'eine Badewanne, die',
'einen Spiegel, der',
'ein Döner Kebab, das',
'einen Fußball, den',
'eine Frisbee, die',
'eine Puppe, die',
'eine Möglichkeit, ein Baby zu tragen, die',
'eine Möglichkeit, um sich auf Prüfungen vorzubereiten, die',
'einen Flash Mob, den',
'eine Ampel, die',
'eine Möglichkeit, öffentliche Verkehrsmittel zu nutzen, die',
'eine Möglichkeit, Reisen zu planen, die',
'eine Visitenkarte, die',
'ein Mikrofon, das',
'eine Möglichkeit, den Weg beschrieben zu bekommen, die',
'einen Wäschereinigugsdienst, den',
'eine Toilette, die',
'ein Haustier, das',
'einen Cocktail, den',
'einen Hammer, den',
'einen Bleistift, den',
'einen Grabstein, den',
'ein Fernglas, das',
'eine Schreibmaschine, die',
'eine Möglichkeit, um einen Brief zu schreiben, die',
'einen Feuerwerkskörper, den',
'eine Wasserflasche, die',
'einen Brunnen, den',
'eine Schaukel, die',
'ein Dessert, das',
'einen Rock, den',
'einen Löffel, den',
'ein Messer, das',
'ein Tasse Kaffee, den',
'eine Statue, die',
'eine Tätowierung, die',
'eine Nagelpolitur, die',
'einen Reisepass, den',
'eine Münze, die',
'einen Hut, den',
'ein Telefon, das',
'einen Plattenspieler, den',
'ein Puzzle, das',
'eine Kerze, die',
'eine Speisekarte, die',
'einen Grill, den',
'eine Dusche, die',
'ein Stück Seife, das',
'ein Handtuch, das',
'eine Möglichkeit, um Dein Haus zu reinigen, die',
'eine Möglichkeit, sich vorzustellen, die',
'eine Möglichkeit, um Videos zu bearbeiten, die',
'einen Blumenstrauß, den',
'einen Hamburger, den',
'einen Schal, den',
'einen Verkaufsautomaten, den',
'eine Regenjacke, die',
'eine Schriftart, die',
'einen Snack, den',
'einen Drucker, den',
'ein Flugticket, das',
'eine Möglichkeit, um deine Nase zu putzen, die',
'eine Möglichkeit, um Ameisen loszuwerden, die',
'eine Picknickdecke, die',
'eine Wasserpistole, die',
'eine Gießkanne, die',
'eine Büroklammer, die',
'ein Lesezeichen, das',
'Unterwäsche, die',
'eine Dating-App, die',
'einen Fernseher, den',
'einen mobilen Imbiss, den',
'einen Toaster, den',
'eine Socke, die',
'ein Fahrrad, das',
'ein Diplom, das',
'ein Lehrbuch, das',
'eine Mittagsmahlzeit für Schulen, die',
'einen Handschuh, den',
'einen Weihnachtsschmuck, den',
'ein Minzbonbon, das'
]


CONSTRAINT = [
'illegal ist',
'Du nicht durch die Sicherheitkontrolle am Flughafen nehmen kannst'
'Deine Nachbarn verrückt macht',
'Du in der U-Bahn benutzen kannst',
'Deinen Großeltern missfallen würde',
'nicht funktioniert',
'süß ist',
'Dich schwitzen lässt',
'eine langsame, mittlere, schnelle und turbo-Einstellungen hat',
'eine helle, mittlere und dunkle Einstellung hat',
'mild, mittel oder scharf sein kann',
'eine kalte, warme und heiße Temperatur haben kann',
'kurz, mittel und lang sein kann',
'klein, mittel und groß sein kann',
'mindestens 5 Personen zum Gebrauch benötigt',
'für eine/n Essensliebhaber/in (Foodie)',
'für eine/n Kunstliebhaber/in',
'für einen Sportfan',
'Dich nostalgisch werden lässt',
'Schwindelgefühle erzeugt',
'Du nicht kontrollieren kannst'
'viel komplizierter ist, als es eigentlich sein müsste',
'für ein Baby',
'Deinen Fingern eine (sinnvolle) Beschäftigung gibt'
'Dir die mit der Nutzung verbundene Umweltbelastung veranschaulicht',
'sich von alleine bewegt',
'gruselig ist',
'für Touristen',
'in Deine Privatsphäre eindringt',
'Dir ein Sicherheitsgefühl verschafft',
'zur Selbstverteidigung verwendet werden kann',
'sehr zerbrechlich ist',
'wirklich verwirrend ist',
'Du mit Deinen Füßen nutzen kannst'
'Du auf deinem Kopf tragen kannst',
'auf Deinen Atem reagiert'
'auf Sprachbefehle reagiert',
'Dir Punkte / Belohnungen für die Benutzung einbringt',
'für eine gemeinsame Wohnung',
'für jemanden in großer Eile',
'Du werfen kannst'
'Du treten / kicken kannst',
'gute Laune erzeugt',
'laut ist',
'Dich warm hält',
'Dich abkühlt',
'sich den Jahreszeiten anpasst',
'jede Woche zu Dir nach Hause geliefert wird',
'für eine/n Arktisforscher/in',
'eine geistige Herausforderung darstellt',
'mit mindestens zwei Rädern',
'Du in der Wüste benutzen kannst',
'in Deine Tasche passt',
'von der Decke hängt',
'wegwerfbar ist',
'auch als Mode(accessoire) funktioniert',
'sich entsprechend Deines Standortes ändert'
'essbar ist',
'die Menschen anregt, freundlich zu Fremden zu sein',
'Deinen Geruchssinn anspricht',
'aus Materialien besteht, die man leicht draußen finden kann',
'von Eltern zusammen mit ihren Kindern genutzt werden kann',
'sich jeden Tag ein bisschen verändert',
'auf Vollmond reagiert',
'für Weihnachten',
'für den Strand',
'man in einen Kinderwagen integieren kann',
'mit einem Streichholz angezündet werden muss',
'Dich betrunken macht',
'Dich aufweckt'
'gut für Deine Zähne ist',
'für eine/n 6-Jährige/n'
'für eine/n Tiefsee-Taucher/in',
'für eine/n 80-Jährige/n'
'für einen Teenager',
'für eine Gruppe von Freunden',
'man jedes Mal neu zusammengebauen muss, wenn man es benutzt',
'Dich beruhigt'
'in ein Auto integriert werden kann',
'in ein Fahrrad integriert werden kann',
'in einen Flugzeugsitz integriert werden kann',
'Dir etwas über Wissenschaft beibringt',
'Dir etwas über Geschichte beibringt',
'Dir eine andere Sprache beibringt',
'für einen Hund',
'für einen Affen',
'Dir zu neuen Ausdruckformen verhilft'
'Du mit geschlossenen Augen benutzen kannst',
'virtuelle Realität nutzt',
'Dir einen Adrenalinschub verpasst',
'Du mieten kannst'
'Deine Hand-Augen-Koordination fördert',
'aufblasbar ist',
'ferngesteuert ist',
'auf Deine Herzfrequenz reagiert',
'auf Temperatur reagiert',
'lauter bunt blinkende Lichter besitzt',
'Du im Bad nutzen kannst',
'Du im Bett nutzen kannst',
'romantisch ist',
'Dich wütend macht',
'niedlich ist',
'sehr hygienisch ist',
'Dir dabei hilft, Geld zu sparen',
'auf das Wetter reagiert',
'nur nachts funktioniert',
'nur nach voriger Vereinbarung eines Termins verwendet werden kann',
'Dir beim Einschlafen hilft',
'Dir etwas über Politik beibringt',
'süchtig macht',
'lebendig ist',
'biologisch abbaubar ist',
'zum Teilen ermuntert',
'ein Statussymbol ist',
'für eine/n Backpacker/in',
'Du auf Reisen nutzen kannst',
'farbcodiert ist',
'sehr leise ist',
'peinlich für Dich ist',
'Dein Selbstbewusstsein steigert',
'für einen König oder eine Königin',
'ein Denkmal für eine bedeutende Persönlichkeit ist',
'für eine/n Patient/in im Krankenhaus',
'für eine/n Taxifahrer/in',
'für eine/n Steinmetz/in'
'freundlich und sanft ist',
'für einen Rockstar',
'für eine/n Schullehrer/in',
'für eine/n Marathonläufer/in',
'für eine/n Kletterer/in',
'für jemanden, der/die gerade ein Baby bekommen hat',
'für jemanden, der/die gerade geheiratet hat',
'für jemanden, der/die gerade in Rente gegangen ist',
'ein Geheimnis bewahren kann',
'Sonnenenergie nutzt',
'Dein Arzt Dir verschreiben kann',
'musikalisch ist',
'an Deinen Körper ergänzt',
'mit Diesel betrieben wird',
'für einen Delphin',
'Dein/e Chef/in nicht genehmigen würde',
'Dir hilft, Deine persönlichen Daten sicher zu halten',
'Dir hilft, Geld zu verdienen'
]
